### PR TITLE
Develop b92 v4.0.3.0

### PR DESCRIPTION
**Pull request by charlie-ai**
1. update header file form B92_ble_multiple_connection_sdk_V4_0_3_0 SDK
2. update pm module using old pm src.and old sdk version:v4.0.2.0(ER)
3. we need to update ble lib too.

### CODE REVIEW

**Review by andriy-bilynskyy — APPROVED** [review]

**Comment by andriy-bilynskyy** [comment]
Please, create PR for library at first, because for now it's in some your branch which could be deleted.

**Review by s07641069 — APPROVED** [review]

**Comment by andriy-bilynskyy** [comment]
Latest B92 BLE lib: 6b570e2932d00aa7d06a84203a423b610ab18425

**Comment by andriy-bilynskyy** [comment]
Could you squash all these commits (it's not possible to check the build in the middle) and set correct library link ([6b570e2932d00aa7d06a84203a423b610ab18425](https://github.com/telink-semi/zephyr_hal_telink_b91_ble_lib/commit/6b570e2932d00aa7d06a84203a423b610ab18425))

**Comment by andriy-bilynskyy** [comment]
BLE library is merged: 794ab4bd0e388d885f18afeeb6695c86f35ea7ca
Please update BLOB file

**Comment by haiwentelink** [comment]
already changed, can merge

**Review by andriy-bilynskyy — APPROVED** [review]

**Comment by andriy-bilynskyy** [comment]
Plese update HAL submodule 8e22fad3c938f4ea2266293897d8b8ea47e566a0

**Pull request merged**
